# Generated by Django 3.2.7 on 2021-10-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_place2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place2',
            old_name='desc2',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='place2',
            old_name='img2',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='place2',
            old_name='name2',
            new_name='name',
        ),
    ]
