# Generated by Django 3.2.10 on 2021-12-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile_no',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
