# Generated by Django 3.2.10 on 2021-12-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0002_auto_20211210_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile_no',
            field=models.CharField(max_length=50),
        ),
    ]
